services:
  - type: web
    name: omcgestao
    runtime: node
    buildCommand: npm install && prisma generate && prisma migrate deploy && next build
    startCommand: next start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 22.x
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
